#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🐶 Husky Pre-Commit Hook'

echo '1/3 TypeScript'
npm run tsc:check

echo '2/3 Linting'
npm run lint-staged

echo '3/3 package.json'
npm run sort-package-json:check
